import Head from "next/head";
import HomeLayout from "../components/Layout/Home";
import { GetStaticProps } from "next";
import { Container } from "../styles/Home";

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://restcountries.eu/rest/v2/all");
  const countries = await res.json();

  return {
    props: {
      countries,
    },
  };
};

interface Props {
  countries;
}

const Home: React.FC<Props> = ({ countries }) => {
  return (
    <div>
      <Head>
        <title>World Ranks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Container>
        <HomeLayout countries={countries} />
      </Container>
    </div>
  );
};
export default Home;
